services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: /api          
    ports:
      - "8080:80"                    
    depends_on:
      - api
      - minio

  api:
    build:
      context: .                     
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - littlemoments            
    expose:
      - "8173"                       
    ports:
      - "8173:8173"                  
    environment:
      LM_S3_ENDPOINT: http://minio:9000
      LM_S3_REGION: us-east-1
      LM_S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      LM_S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      LM_S3_BUCKET_PHOTOS: photos
      LM_S3_PUBLIC_BASE: http://localhost:9000
      LM_WEB_ORIGINS: http://localhost:8080,http://littlemoments:8080
    volumes:
      - app_data:/app/data             
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"                 
      - "9001:9001"                  
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

volumes:
  app_data:
  minio_data: